### ISSUE TITLE
Can't save schedule updates when there is a CROM pattern

### ISSUE THREAD

**Issue by mckayERP** [mckayERP/FlightCollege#1]
---

===========> GridTable.dataSave: Persistency Issue - AD_Scheduler: it/sauronsoftware/cron4j/SchedulingPattern [16]
java.lang.NoClassDefFoundError: it/sauronsoftware/cron4j/SchedulingPattern
    at org.compiere.model.MScheduler.beforeSave(MScheduler.java:265)
    at org.compiere.model.PO.save(PO.java:2096)
    at org.compiere.model.GridTable.dataSavePO(GridTable.java:2139)
    at org.compiere.model.GridTable.dataSave(GridTable.java:1474)
    at org.compiere.model.GridTab.dataSave(GridTab.java:986)
    at org.compiere.apps.APanel.cmd_save(APanel.java:2050)
    at org.compiere.apps.APanel.actionPerformed(APanel.java:1713)
    at org.compiere.apps.AppsAction.actionPerformed(AppsAction.java:286)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
    at java.awt.Component.processMouseEvent(Component.java:6535)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6300)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4891)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4713)
caused by: java.lang.ClassNotFoundException: it.sauronsoftware.cron4j.SchedulingPattern
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at org.compiere.model.MScheduler.beforeSave(MScheduler.java:265)
    at org.compiere.model.PO.save(PO.java:2096)
    at org.compiere.model.GridTable.dataSavePO(GridTable.java:2139)
    at org.compiere.model.GridTable.dataSave(GridTable.java:1474)
    at org.compiere.model.GridTab.dataSave(GridTab.java:986)
    at org.compiere.apps.APanel.cmd_save(APanel.java:2050)
    at org.compiere.apps.APanel.actionPerformed(APanel.java:1713)
    at org.compiere.apps.AppsAction.actionPerformed(AppsAction.java:286)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
    at java.awt.Component.processMouseEvent(Component.java:6535)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6300)

Host = MHIW947 : 1099 (2015-03-01)

Database = localhost : 5432 / adempiere
Schema = adempiere
User/Contact = System
Role = System Administrator
Client = System
Organization = *
Date = 2016-05-29 00:00:00
Printer = Send To OneNote 2010
Implementation Vendor = ${ADEMPIERE_VENDOR}
Implementation Version = ${ADEMPIERE_VERSION} 20160528-1638
AdempiereHome = C:\adempiere
AdempiereProperties = C:\adempiere\Adempiere.properties
Language=[English,Locale=en_US,AD_Language=en_US,DatePattern=MM/DD/YYYY,DecimalPoint=true]
MClient[0-SYSTEM]
Multi Lingual Documents = true
BaseLanguage = true/true
Java HotSpot(TM) 64-Bit Server VM 25.60-b23
java.io.tmpdir=C:\Users\MICHAE~1.MCK\AppData\Local\Temp\
Windows 7 6.1 Service Pack 1
Max Heap = 455M
Allocated Heap = 195M
Free Heap = 70M
Active Threads = 8
=== Environment === -1566085491
ADempiere(r) OFC Custom 3.8.0_2_2015-03-01 -Smart Suite ERP,CRM and SCM- (c) 1999-2015 ADempiere(r); Implementation: ${ADEMPIERE_VERSION} 20160528-1638 - ${ADEMPIERE_VENDOR}
MHIW947/192.168.2.44
MHIW947{localhost-adempiere-adempiere} adempiere@jdbc:postgresql://localhost:5432/adempiere?encoding=UNICODE
Database=PostgreSQL - 9.4.5 - Driver  =PostgreSQL Native Driver - PostgreSQL 9.3 JDBC4.1 (build 1102) - via DataSource
DB_PostgreSQL[null]
AppsServerOK=true, DatabaseOK=true

=== Context ===
# AD_Client_ID == 0
# AD_Client_Name == System
# AD_Language == en_US
# AD_Org_ID == 0
# AD_Org_Name == *
# AD_PrintColor_ID == 100
# AD_PrintFont_ID == 130
# AD_PrintPaper_ID == 100
# AD_PrintTableFormat_ID == 100
# AD_Role_ID == 0
# AD_Role_Name == System Administrator
# AD_SearchDefinition_ID == 50000
# AD_Session_ID == 1013664
# AD_User_ID == 0
# AD_User_Name == System
# C_ConversionType_ID == 114
# C_Country_ID == 100
# C_Region_ID == 142
# C_UOM_ID == 100
# Date == 2016-05-29 00:00:00
# IsLiberoEnabled == Y
# IsLiberoWMEnabled == Y
# M_Warehouse_ID == 0
# Printer == Send To OneNote 2010
# SalesRep_ID == 0
# ShowAcct == N
# ShowAdvanced == Y
# ShowTrl == Y
# StdPrecision == 2
# SysAdmin == Y
# User_Level == S
# User_Org == 0
# YYYY == Y

0|WindowName == &Menu
2|0|AD_Client_ID == 0
2|0|AD_Org_ID == 0
2|0|AD_Process_ID == 1000008
2|0|AD_Scheduler_ID == 1000004
2|0|AD_Table_ID == 0
2|0|Created == 2010-03-13 22:33:34
2|0|CreatedBy == 0
2|0|CronPattern == */5 \* \* \* *
2|0|DateLastRun == 2016-05-29 06:05:03
2|0|DateNextRun == 2016-05-29 06:10:00
2|0|Description == Import Open flights
2|0|Frequency == 5
2|0|FrequencyType == M
2|0|IsActive == N
2|0|IsIgnoreProcessingTime == N
2|0|KeepLogDays == 2
2|0|Name == OFC_Import_Open_Flights
2|0|Processing == N
2|0|Record_ID == 0
2|0|ScheduleType == C
2|0|Supervisor_ID == 0
2|0|Updated == 2016-05-29 06:05:03
2|0|UpdatedBy == 0
2|0|_TabInfo_AD_Tab_ID == 589
2|0|_TabInfo_AD_Table_ID == 688
2|0|_TabInfo_AccessLevel == 6
2|0|_TabInfo_KeyColumnName == AD_Scheduler_ID
2|0|_TabInfo_Name == Schedule Process
2|0|_TabInfo_SQL == SELECT AD_Client_ID,AD_Org_ID,Name,Description,IsActive,AD_Process_ID,ScheduleType,FrequencyType,Frequency,IsIgnoreProcessingTime,CronPattern,Supervisor_ID,KeepLogDays,DateLastRun,DateNextRun,AD_Table_ID,Processing,Record_ID,AD_Scheduler_ID,Created,CreatedBy,Updated,UpdatedBy FROM AD_Scheduler WHERE AD_Scheduler.AD_Client_ID=0 AND AD_Scheduler.AD_Org_ID=0 AND (AD_Scheduler.AD_Scheduler_ID IS NULL OR AD_Scheduler.AD_Scheduler_ID NOT IN ( SELECT Record_ID FROM AD_Private_Access WHERE AD_Table_ID = 688 AND AD_User_ID <> 0 AND IsActive = 'Y' )) ORDER BY Name
2|0|_TabInfo_TabLevel == 0
2|1|_TabInfo_AD_Tab_ID == 590
2|1|_TabInfo_AD_Table_ID == 698
2|1|_TabInfo_AccessLevel == 6
2|1|_TabInfo_Name == Parameter
2|1|_TabInfo_TabLevel == 1
2|2|_TabInfo_AD_Tab_ID == 639
2|2|_TabInfo_AD_Table_ID == 704
2|2|_TabInfo_AccessLevel == 6
2|2|_TabInfo_KeyColumnName == AD_SchedulerRecipient_ID
2|2|_TabInfo_Name == Scheduler Recipient
2|2|_TabInfo_TabLevel == 1
2|3|_TabInfo_AD_Tab_ID == 591
2|3|_TabInfo_AD_Table_ID == 687
2|3|_TabInfo_AccessLevel == 6
2|3|_TabInfo_KeyColumnName == AD_SchedulerLog_ID
2|3|_TabInfo_Name == Log
2|3|_TabInfo_TabLevel == 1
2|AD_Client_ID == 0
2|AD_Org_ID == 0
2|AD_Process_ID == 1000008
2|AD_Scheduler_ID == 1000004
2|AutoCommit == Y
2|AutoNew == N
2|BaseTable_ID == 688
2|Created == 2010-03-13 22:33:34
2|CreatedBy == 0
2|CronPattern == */5 \* \* \* *
2|DateLastRun == 2016-05-29 06:05:03
2|DateNextRun == 2016-05-29 06:10:00
2|Description == Import Open flights
2|Frequency == 5
2|FrequencyType == M
2|IsActive == N
2|IsIgnoreProcessingTime == N
2|IsSOTrx == Y
2|KeepLogDays == 2
2|Name == OFC_Import_Open_Flights
2|Processing == N
2|ScheduleType == C
2|Supervisor_ID == 0
2|Updated == 2016-05-29 06:05:03
2|UpdatedBy == 0
2|WindowName == Scheduler
AutoCommit == Y
AutoNew == N
P103|Type == S
P53004|AD_Org_ID == 0
P53005|Action == C
P53032|AD_Org_ID == 0
P53034|AD_Org_ID == 0
P53035|AD_Org_ID == 0
java.naming.provider.url == jnp://MHIW947:1099
org.adempiere.security.principal == org.compiere.db.SecurityPrincipal@554ec0a4
org.compiere.model.DefaultRole == MRole[0,System Administrator,UserLevel=S  ,AD_Client_ID=0,AD_Org_ID=0]
org.compiere.util.CLogErrorBuffer.errors == [java.util.logging.LogRecord@b4947f7]
org.compiere.util.CLogErrorBuffer.history == [[Ljava.util.logging.LogRecord;@7590b071]
org.compiere.util.CLogErrorBuffer.issueError == true
org.compiere.util.CLogErrorBuffer.logs == [java.util.logging.LogRecord@b4947f7]

=== System ===
ADEMPIERE_HOME=C:\adempiere
awt.toolkit=sun.awt.windows.WToolkit
com.mchange.v2.log.MLog=com.mchange.v2.log.FallbackMLog
file.encoding=UTF8
file.encoding.pkg=sun.io
file.separator=\
java.awt.graphicsenv=sun.awt.Win32GraphicsEnvironment
java.awt.printerjob=sun.awt.windows.WPrinterJob
java.class.path=C:\adempiere\lib\Adempiere.jar;C:\adempiere\lib\AdempiereCLib.jar;C:\adempiere\lib\CompiereJasperReqs.jar;
java.class.version=52.0
java.endorsed.dirs=C:\Program Files\Java\jdk1.8.0_60\jre\lib\endorsed
java.ext.dirs=C:\Program Files\Java\jdk1.8.0_60\jre\lib\ext;C:\Windows\Sun\Java\lib\ext
java.home=C:\Program Files\Java\jdk1.8.0_60\jre
java.io.tmpdir=C:\Users\MICHAE~1.MCK\AppData\Local\Temp\
java.library.path=C:\Program Files\Java\jdk1.8.0_60\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Program Files\Java\jdk1.8.0_60\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseHg\;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\PuTTY;C:/Program Files/PostgreSQL/9.4\bin;C:\dev\tools\apache-ant-1.9.6\bin;.
java.runtime.name=Java(TM) SE Runtime Environment
java.runtime.version=1.8.0_60-b27
java.specification.name=Java Platform API Specification
java.specification.vendor=Oracle Corporation
java.specification.version=1.8
java.vendor=Oracle Corporation
java.vendor.url=http://java.oracle.com/
java.vendor.url.bug=http://bugreport.sun.com/bugreport/
java.version=1.8.0_60
java.vm.info=mixed mode
java.vm.name=Java HotSpot(TM) 64-Bit Server VM
java.vm.specification.name=Java Virtual Machine Specification
java.vm.specification.vendor=Oracle Corporation
java.vm.specification.version=1.8
java.vm.vendor=Oracle Corporation
java.vm.version=25.60-b23
jboss.remoting.version=22
line.separator=

os.arch=amd64
os.name=Windows 7
os.version=6.1
path.separator=;
sun.arch.data.model=64
sun.awt.enableExtraMouseButtons=true
sun.boot.class.path=C:\Program Files\Java\jdk1.8.0_60\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_60\jre\lib\rt.jar;C:\Program Files\Java\jdk1.8.0_60\jre\lib\sunrsasign.jar;C:\Program Files\Java\jdk1.8.0_60\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_60\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_60\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_60\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_60\jre\classes
sun.boot.library.path=C:\Program Files\Java\jdk1.8.0_60\jre\bin
sun.cpu.endian=little
sun.cpu.isalist=amd64
sun.desktop=windows
sun.io.unicode.encoding=UnicodeLittle
sun.java.command=org.compiere.Adempiere
sun.java.launcher=SUN_STANDARD
sun.jnu.encoding=Cp1252
sun.management.compiler=HotSpot 64-Bit Tiered Compilers
sun.os.patch.level=Service Pack 1
sun.stderr.encoding=cp850
sun.stdout.encoding=cp850
user.country=CA
user.dir=C:\Adempiere
user.home=C:\Users\michael.mckay
user.language=en
user.name=michael.mckay
user.script=
user.timezone=America/New_York
user.variant=

**Comment by mckayERP** [comment]
This is an issue with the ADempiere trunk.
